* Tratamiento de datos
** Notas:
Marcar: Objetivo de los datos para que se quiere obtener de ellos
Proxima semana todo hecho
** Primer dia
- Charla de profesor la prox semana
** Talk Notes - Big data and Real Time Bidding
Charla interesante
** Extracción de conocimiento de base de datos
- Etapas
Como saber que las reglas que calsifican al cliente son correctas

if (....) then NO_PAGA
if (....) then PAGA
if (....) then NO_PAGA

| Clientes | Variables | PAGA HECHO | PREDICHO DEL SISTEMA       |
|----------+-----------+------------+----------------------------|
| ID1      | ....      | Si         | NO                         |
| ID2      | ...       | Si         | No                         |
| .....    | ......    | ......     | ....                       |
|----------+-----------+------------+----------------------------|
|          |           |            | 90% de acierto por ejemplo |

Matriz de confusion
| Real\Predicho | Si | No |
| Si            | 20 |  5 |
| No            |  5 | 70 |

La diagonal es % de acierto


** Practica
Weka
Cross-validation se divide los datos en 10 y se usa 1 con para testear contra el resto y se va cambiando el
conjunto con el que se testea, al final se calcula el promedio

Ojo con la unamidad, es cuando se corta, puede que un sub arbol termine con la misma conclusion
pero se abre ya que el algoritmo termina cogiendo el mayor (votacion). Esto se podria otimizar una
vex calculado el arbol.

Analizar el arbol para concluir en conclusiones para el proyecto. Saber el funcionamiento de los algoritmos
para saber como se han obtenido los resultados

Poner todos los datos
** Clasificadores Bayesianos
*** Introducción
*** Desiciones bayesianas
Con el teorema de bayes y teorma total, terminamos por coger la mayor → Hipotesis maxima...
**** Tarea
Muchas varialbes con 3 o 4 valores para representalos pues muy dificil. Para evitarlo se aplica
una transformacion para evitar los 0. Que se hace realmente en esos casos?
*** Clasificador Naïve - Bayes

** Algoritmos genéticos
Descubrimiento de reglas
- If (prediccion cubierto) then jugar si
- If (viento = debil and humedad) then jugar si
- If (viento = fuerte) then jugar no

| Prediccion           | Temp      | Humedad   | Viento    | Jugar     |
| 3 valores            | 2 valores | 2 valores | 2 valores | 2 valores |


Cada variable se representa con un array de 0|1 de la dimension de valores.
 110 00 00 00 10

Se debe ver como 1 despejado o lluvioso, en el caso del consecuente (Jugar)
no tiene sentido 11

*Leer articulos en ingles*

** Árboles de desición(más contenido)

*** Tarea 7
Variables numericas:
- Se puede discretizar, establecer intervalos en la variable
- 

| ID |  11 |   8 |   3 |   1 |   9 |   4 |   2 |   7 |   2 |   5 |  10 |   6 |  14 |  13 |
| X  | 129 | 143 | 148 | 150 | 151 | 152 | 172 | 195 | 211 | 256 | 265 | 275 | 286 | 312 |
|    |  no |  no |  no |  no |  no |  no |  si |  si |  si |  si |  si |  no |  no |  no |
|    |     |     |     |     |     |     |     |     |     |     |     |     |     |     |

h se conje en los puntos donde cambia de si a no y al revez
h == 151.5, 157, 193.5, 270

** Practicas weka 

Correcion de laplace



